### ISSUE TITLE
Port Trac wiki contents to Git

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/docs#1]
We should phase out the old Trac wiki, and port its contents to GitHub instead. (I will push the relevant stuff from the existing `trac.db` SQLite database separately.)

What the dump gives us is the page name, version number, Unix timestamp, Trac author, actual page content, and comment. These should be used as follows:
* page name --> file name (and file path for names that start with "Archive/" etc.)
* version number + comment --> commit message (a la `"Add version " + VERSION + " of page '" + TITLE + "'\n\n" + COMMENT)`
* Unix timestamp --> commit timestamp
* Trac author --> GitHub ID (as far as we know it)
* Page contents --> file contents

For example, a page named `CHinst` by `albert` in version 1 of date `1495729526` should become a *file* of the same name, author `aaaaalbert`, and appropriate commit message / timestamp.

The same page name in version *2* of date `1495814460` should go to *the same file name*, again with appropriate message / timestamp.

Thus, the conversion needs to start with the earliest Trac timestamp, and work its way forward in time.

-----

Here is how I generate the wiki dump (generally following the ideas in https://gist.github.com/sgk/1286682 ):
```python
import sqlite3
import pickle

SQL = '''
  select
      name, version, time, author, text, comment
    from
      wiki w
'''

conn = sqlite3.connect('trac.db')
result = conn.execute(SQL)
outfile = open("trac_wiki_dump.pickle", "wb")
outlist = []
for line in result:
  outlist.append(line)

pickle.dump(outlist, outfile)
outfile.close()
```

**Comment by aaaaalbert** [comment]
@priyam3nidhi: To read the dump in Python, `gunzip` it first, then do
```python
import pickle
wiki_records_list = pickle.load(file("trac_wiki_dump.pickle"))
```
This yields a list of tuples of the described format, over which you can loop etc.

**Comment by aaaaalbert** [comment]
Priyam reports an error reading in the file on her Windows 8.1 machine with Python 2.7.10. @kellender, could you try to replicate?

**Comment by fmetzger** [comment]
Reading the file with the above line of code works without a hitch for me (Windows & latest Python 2.7 release).

**Comment by aaaaalbert** [comment]
Thanks for checking, @fmetzger!

**Comment by XuefengHuang** [comment]
I have trouble reading the file with he above line of code. My machine is OS X 10.11.2. There is the traceback:
```
172-16-25-226:docs-master Xuefeng$ python
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> wiki_records_list = pickle.load(file("trac_wiki_dump.pickle"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```

**Comment by aaaaalbert** [comment]
I'm puzzled! Are we talking about the same `gunzip`ped rendition of the file? From a fresh checkout:
```
$ gunzip -k ./trac_wiki_dump.pickle.gz
$ openssl sha1 *
SHA1(trac_wiki_dump.pickle)= 6f8ab52df6060dadd0edd254ee01b239a14f971d
SHA1(trac_wiki_dump.pickle.gz)= 3fb5aec2054b727f80f7514bcc580a08e73b4e89
$ wc -c *
 42842526 trac_wiki_dump.pickle
 6283583 trac_wiki_dump.pickle.gz
```

**Comment by XuefengHuang** [comment]
Oh, it works now! The issue is that I miss `-k` .

**Comment by aaaaalbert** [comment]
`-k` shouldn't be relevant, this is only so as to *keep* the original gzipped file (rather than removing it after gunzipping, which would be the default). Anyway, thank you for checking!

@priyam3nidhi, looks like a fresh checkout of the repo will fix your problem.

**Comment by priyam3nidhi** [comment]
Yeah, it works now! Working on the loop now.

**Comment by aaaaalbert** [comment]
Done! The wiki contents are all in this repo now! Thanks @priyam3nidhi for your support.
