### ISSUE TITLE
Update django version in CH and CIB installation docs

### ISSUE THREAD

**Issue by lukpueh** [SeattleTestbed/docs#29]
Clearinghouse and Custominstallerbuilder were updated to use Django >1.8. This should also be reflected in the docs.

- Clearinghouse: [change Django installation docs](https://github.com/SeattleTestbed/docs/blob/master/Operating/Clearinghouse/Installation.md#install-django) because of [PR](https://github.com/SeattleTestbed/clearinghouse/pull/167
) (already merged)
- Custominstallerbuilder: [change Django installation docs](https://github.com/SeattleTestbed/docs/blob/master/Operating/CustomInstallerBuilder/Installation.md#install-django) because of [PR](https://github.com/SeattleTestbed/custominstallerbuilder/pull/21) (under review)

**Comment by aaaaalbert** [comment]
Since SeattleTestbed/custominstallerbuilder#21 is merged, I went and cleaned up the CIB docs in 48f0776ceafd32283472ad5b2657462b4eb0b32e.

**Comment by aaaaalbert** [comment]
We're at `1.8.18` in both docs now. Closing!
