### ISSUE TITLE
Loop through AB storage reference monitors on Windows

### ISSUE THREAD

**Issue by wecsam** [SeattleTestbed/docs#35]
Under [this section in the AB storage assignment part two](https://github.com/SeattleTestbed/docs/blob/master/EducationalAssignments/ABStoragePartTwo.md#how-to-run-your-tests-on-many-reference-monitors), it says:

> Then you can type the following in the bash shell to execute the testcases with the reference monitors:
> ```
> for referencemonitor in reference_monitor_*; do for testcase in <net_id>_*; do python repy.py restrictions.default encasementlib.r2py $referencemonitor $testcase; done; done
> ```
> This will print out the output from each program.
>
> If you want to spot the referencemonitor that failed during the test run, you could add debug print statements during run as follows,
> ```
> for referencemonitor in reference_monitor_*; do echo $referencemonitor under test; for testcase in <net_id>_*; do python repy.py restrictions.default encasementlib.r2py $referencemonitor $testcase; done; done
> ```
>
> This will print out the name of each reference monitor before it starts executing the testcases against it.
>
> If you are a Windows user and you create your own solution that does the same thing, please post it on the forum.

Here is the equivalent command on Windows:

    FOR %r IN (reference_monitor_*) DO @FOR %a IN (<net_id>_*) DO @python repy.py restrictions.default encasementlib.r2py %r %a

If you want the code to echo the name of each reference monitor:

    FOR %r IN (reference_monitor_*) DO @(ECHO %r under test & FOR %a IN (<net_id>_*) DO @python repy.py restrictions.default encasementlib.r2py %r %a)

**Comment by aaaaalbert** [comment]
Thank you very much! Is this snippet supposed to be run in the `cmd` shell or in PowerShell?

**Comment by wecsam** [comment]
That snippet is for the CMD shell. Here is the equivalent for PowerShell:

    foreach ($referencemonitor in Get-ChildItem reference_monitor_*) { foreach ($testcase in Get-ChildItem <net_id>_*) { python repy.py restrictions.default encasementlib.r2py $referencemonitor.Name $testcase.Name } }

To echo the name of each reference monitor:

    foreach ($referencemonitor in Get-ChildItem reference_monitor_*) { Write-Host $referencemonitor.Name; foreach ($testcase in Get-ChildItem <net_id>_*) { python repy.py restrictions.default encasementlib.r2py $referencemonitor.Name $testcase.Name } }

**Comment by aaaaalbert** [comment]
Awesome! Do you want to send a Pull Request for this for extra GitHub credit? 😄

**Comment by wecsam** [comment]
I have created a pull request in #36.
