### ISSUE TITLE
Convert files to use Markdown formatting

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/docs#4]
The documentation files should be updated to use Markdown. This involves renaming them to use the `.md` file extension, but also converting the previoous Trac wiki markup.

However, see also #2 --- don't go and blindly convert things. Start with RepyV1/2 docs+tutorial, clearinghouse, custom installer builder docs. Then proceed to the other things.

Any help is appreciated! Just add your GiHub handle and the page you will be converting as a comment below.

**You can use the [tractomd.py](https://github.com/SeattleTestbed/docs/blob/master/tractomd.py)-script for some limited automatic conversion!**

**Comment by lukpueh** [comment]
start with RepyV1/2 docs+tutorial

**Comment by aaaaalbert** [comment]
FYI, #8 converted the RepyV2 tutorial and API docs.

**Comment by aaaaalbert** [comment]
#12 converterd the RepyV1 tutorial and API docs.

**Comment by lukpueh** [comment]
Some converted pages may still point to old trac wiki pages that have not been converted yet. So it is a good idea to check from time to time and update the links if the pages have been updated, e.g. like so when in the docs directory:
```sh
grep -lr --include="*.md" "wiki:\|\.wiki" .
```

**Comment by aaaaalbert** [comment]
Excellent point, we need to check this regularly.

**Comment by aaaaalbert** [comment]
Note: Clearinghouse and Custom Installer Builder docs conversions / updates per #13, #14.

**Comment by lukpueh** [comment]
**Use [tractomd.py](https://github.com/SeattleTestbed/docs/blob/master/tractomd.py)-script for some limited automatic conversion!**

**Comment by aaaaalbert** [comment]
9ce5e758ac94191bf3372806710756b93d097787 converts the "formal installer documentation" and infrastructure architecture document.

**Comment by aaaaalbert** [comment]
8595301d114e69aafb031c7deb125b5c7d41320f converts the Unit Test Framework docs.

**Comment by aaaaalbert** [comment]
#19 converts BaseInstallers, Clearinghouse/Design, CIB API and Usage, Operating/SWUP, and Zenodotus.

**Comment by aaaaalbert** [comment]
@ankitbhatia32 is going for EducationalAssignments and Programming.

**Comment by ankitbhatia32** [comment]
I have converted almost all the folder and files except the ATTACHMENTS. Here is the link:
https://github.com/ankitbhatia32/docs

**Comment by aaaaalbert** [comment]
No `.wiki` files are left in this repo, so I'm closing this issue. Thank you for your contributions!
