### ISSUE TITLE
Add an intro / TOC page

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/docs#5]
We should have a "landing page" of sorts so that readers are guided through / pointed at appropriate places to start learning about Seattle. The [Trac wiki start page](https://www.usenix.org/conference/osdi12) could be a starting point.

**Comment by aaaaalbert** [comment]
Fixed in 7085bd772937e68318c26713ee2ce55c80a699a1.

**Comment by vladimir-v-diaz** [comment]
The landing page lists Justin's old poly.edu email address.  Not sure if this older email address still works, but it might be safer to use: jcappos@nyu.edu

A link to the group page might also be convenient:
https://groups.google.com/forum/#!forum/seattle-users

**Comment by vladimir-v-diaz** [comment]
Are you planning to add an installation/build section to the landing page that outlines how users are expected to build the different Seattle components?  For example: https://github.com/SeattleTestbed/buildscripts#buildscripts

I think the [build instructions](https://seattle.poly.edu/wiki/BuildInstructions) should be prominently displayed on the landing page somewhere.  They might be there, but they didn't jump out to me.

**Comment by aaaaalbert** [comment]
f25b51e6f46904b397a5ab42f7e9bd02d4752a4a addresses Justin's email and the Google Groups link. Thanks!

Re build instructions, it's difficult to add everything that we think is relevant to that page already. Currently, I'm linking off to the contributor's sub-page in the list of topics right on top of the README. I'm not settled yet in terms of who we think the biggest target audience for this landing page will be. (I for one am fine with pointing folks to pages lower down in the hierarchy, and assume the landing page is mostly for total newcomers / passer-bys.)

**Comment by JustinCappos** [comment]
Perhaps using a project email (or even Albert's email) would be better...
