### ISSUE TITLE
Broken Link To Paper

### ISSUE THREAD

**Issue by SemicolonExpected** [SeattleTestbed/docs#56]
Hi, I noticed that you had a broken link in ABStorageOne assignment to one of your papers

> The following link is an excellent source for information about security layers: [http://isis.poly.edu/~jcappos/papers/cappos_seattle_ccs_10.pdf]

**Comment by JustinCappos** [comment]
I believe this was fixed in: https://github.com/SeattleTestbed/docs/commit/621e14e48f56a9f60c2a32cc8bf9feef95682cce
