### ISSUE TITLE
Reproduce grants/endowment footer?

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/docs#7]
The Trac wiki's footer reads
> This material is based upon work supported by the National Science Foundation under Grant No. (CNS-0834243). Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of GPO Technologies, Corp., the GENI Project Office, or the National Science Foundation.

@justincappos, shall we add a `grants` (or similar) page to the docs repo (or some other place)?

**Comment by JustinCappos** [comment]
Okay, first minor thing.  We're supposed to list more grants than this.
See the footer of seattle.poly.edu:

This material is based upon work supported by the National Science
Foundation under Grant Numbers (0834243, 1205415, and 1223588). Any
opinions, findings, and conclusions or recommendations expressed in this
material are those of the author(s) and do not necessarily reflect the
views of the National Science Foundation.

Ideally this would be part of the footer, etc. but we can adjust and have a
separate page if needed.

Justin

**Comment by aaaaalbert** [comment]
That difference between the grants that the wiki and the web root list is interesting.

Anyway, I'll figure out a place for the info.

**Comment by aaaaalbert** [comment]
Note: I fixed the Trac wiki note to include the other grant numbers.
