### ISSUE TITLE
`tractomd` triple single-quote problem

### ISSUE THREAD

**Issue by aaaaalbert** [SeattleTestbed/docs#9]
The [Trac-to-Markdown conversion script](../blob/master/tractomd.py) doesn't convert bold correclty:
Input: `'''This''' should be '''bold''', but '''it''' still isn't quite.`
Output: `'''This''' should be **bold''', but '''it** still isn't quite.`

The problem seems to be that triple single-quotes [must be prefixed and suffixed by a space](https://github.com/SeattleTestbed/docs/commit/ea792ffbdc6f5221fb06c796007805372aa44391#diff-0ee9b25e6d3fd0e92a7a9c67cfdb512dR71) for the current regex to work.

The bold/italic regexes also add a leading/trailing space to the Markdown rendition of emphasized words.

**Comment by lukpueh** [comment]
Easy to fix, just use `negative lookbehind assertion`.
The space hack was initially introduced to prevent two urls on a line from being italicized.
E.g. "http://this.is.not.italic http://got.it" --> "http:*this.is.not.italic http:*got.it"
PR #11 fixes these problems.
